# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='create_time',
            field=models.CharField(max_length=55, verbose_name='创建时间'),
        ),
    ]
