# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bah', models.CharField(default='豫ICP备18037195号-1', max_length=33, verbose_name='备案号')),
                ('baLink', models.CharField(default='http://www.miibeian.gov.cn', max_length=53, verbose_name='备案链接')),
                ('title', models.CharField(default='python圈 | (Circle) 专注python相关技术', max_length=66, verbose_name='标题')),
                ('desc', models.CharField(default='科技界的一股清流，情怀程序yuan！', max_length=99, verbose_name='口号')),
            ],
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33, verbose_name='友情链接名称')),
                ('link', models.CharField(max_length=100, verbose_name='友情链接')),
                ('head', models.ImageField(blank=True, null=True, upload_to='static/common/friend/', verbose_name='友链图标')),
                ('sort', models.IntegerField(help_text='数字越大越往前', verbose_name='排序')),
            ],
        ),
    ]
