# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=223, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='static/articles/cover', verbose_name='文章封面图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article_from', models.CharField(choices=[(1, '原创'), (2, '转载'), (3, '翻译')], max_length=16, verbose_name='文章来源')),
                ('count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('zan_num', models.IntegerField(default=0, verbose_name='点赞量')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='Article_count',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章浏览记录',
                'verbose_name_plural': '文章浏览记录',
            },
        ),
        migrations.CreateModel(
            name='Article_zan_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章点赞记录',
                'verbose_name_plural': '文章点赞记录',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=56, verbose_name='文集名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='文集状态')),
                ('sort', models.IntegerField(default=0, verbose_name='文集排序')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='文章类别名称')),
                ('cover', models.ImageField(default='/static/img/logo.png', upload_to='static/articles/type_cover', verbose_name='文章分类图像')),
                ('intro', models.TextField(verbose_name='文章类别描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('favorites_articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': '文章收藏记录',
                'verbose_name_plural': '文章收藏记录',
            },
        ),
    ]
