# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20190805_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=56, verbose_name='文集名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='文集状态')),
                ('sort', models.IntegerField(default=0, verbose_name='文集排序')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文集创建者')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='article_count',
            options={'verbose_name': '文章浏览记录', 'verbose_name_plural': '文章浏览记录'},
        ),
        migrations.AlterModelOptions(
            name='article_zan_log',
            options={'verbose_name': '文章点赞记录', 'verbose_name_plural': '文章点赞记录'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': '文章收藏记录', 'verbose_name_plural': '文章收藏记录'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_from',
            field=models.CharField(choices=[('1', '原创'), ('2', '转载'), ('3', '翻译')], max_length=16, verbose_name='文章来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/articles/cover', verbose_name='文章封面图'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='cover',
            field=models.ImageField(default='static/img/logo.png', upload_to='static/articles/type_cover', verbose_name='文章分类图像'),
        ),
        migrations.AddField(
            model_name='article',
            name='articleGroup',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleGroup', verbose_name='关联文集'),
            preserve_default=False,
        ),
    ]
