# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190810_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_from',
            field=models.CharField(choices=[('1', '原创'), ('2', '转载'), ('3', '翻译')], max_length=16, verbose_name='文章来源'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='cover',
            field=models.ImageField(default='static/img/logo.png', upload_to='static/articles/type_cover', verbose_name='文章分类图像'),
        ),
    ]
